"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { fromRecord, resources, toPayload } from "../lib/resources";

function blank(fields){return Object.fromEntries(fields.map(([name,,type,,options])=>[name,type==='checkbox'?false:type==='select'?options[0]:""]));}

export default function ContentManager({resource,initialRows}){
  const config=resources[resource];const router=useRouter();const [rows,setRows]=useState(initialRows);const [editing,setEditing]=useState(null);const [form,setForm]=useState(blank(config.fields));const [message,setMessage]=useState("");
  function start(row){setEditing(row?.id||'new');setForm(row?fromRecord(resource,row):blank(config.fields));setMessage("");}
  async function save(event){event.preventDefault();const isNew=editing==='new';const payload=toPayload(resource,form);const file=event.currentTarget.media?.files?.[0];let uploadedId=null;if(file){const media=new FormData();media.set('file',file);media.set('altText',form.title||form.name||'Portfolio media');const upload=await fetch('/api/admin/media',{method:'POST',body:media});const uploaded=await upload.json();if(!upload.ok){setMessage(uploaded.error);return;}uploadedId=uploaded.data.id;payload[resource==='projects'?'image_media_id':'file_media_id']=uploadedId;}const response=await fetch(`/api/admin/${resource}${isNew?'':`/${editing}`}`,{method:isNew?'POST':'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok){if(uploadedId)await fetch(`/api/admin/media/${uploadedId}`,{method:'DELETE'});setMessage(result.error);return;}const previousId=resource==='projects'?form.image_media_id:resource==='certifications'?form.file_media_id:null;if(uploadedId&&previousId)await fetch(`/api/admin/media/${previousId}`,{method:'DELETE'});setMessage("Saved.");setEditing(null);router.refresh();location.reload();}
  async function remove(id){if(!confirm(`Delete this ${config.singular}?`))return;await fetch(`/api/admin/${resource}/${id}`,{method:'DELETE'});setRows(rows.filter((row)=>row.id!==id));}
  async function move(index,direction){const target=index+direction;if(target<0||target>=rows.length)return;const next=[...rows];[next[index],next[target]]=[next[target],next[index]];setRows(next);await fetch(`/api/admin/${resource}/order`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:next.map((r)=>r.id)})});router.refresh();}
  return <><div className="page-heading"><div><p className="eyebrow">Content</p><h1 className="admin-title">{config.label}</h1></div><button className="button no-margin" onClick={()=>start()}>Add {config.singular}</button></div>{message&&<p role="status" className="form-success">{message}</p>}{editing&&<form className="panel editor-form" onSubmit={save}>{config.fields.map(([name,label,type='text',required,options])=><label className={type==='checkbox'?'check-field':'field'} key={name}>{type==='checkbox'?<><input type="checkbox" checked={Boolean(form[name])} onChange={(e)=>setForm({...form,[name]:e.target.checked})}/><span>{label}</span></>:<><span>{label}</span>{type==='textarea'?<textarea value={form[name]??''} required={required} onChange={(e)=>setForm({...form,[name]:e.target.value})}/>:type==='select'?<select value={form[name]} onChange={(e)=>setForm({...form,[name]:e.target.value})}>{options.map((o)=><option key={o} value={o}>{o.replace('_',' ')}</option>)}</select>:['image','pdf'].includes(type)?<><input name="media" type="file" accept={type==='image'?'image/jpeg,image/png,image/webp':'application/pdf'}/>{form[name]&&<small>A current file is attached. Choose a file to replace it.</small>}</>:<input type={type} value={form[name]??''} required={required} onChange={(e)=>setForm({...form,[name]:e.target.value})}/>}</>}</label>)}<div className="form-actions"><button className="button no-margin" type="submit">Save</button><button className="secondary-button" type="button" onClick={()=>setEditing(null)}>Cancel</button></div></form>}{rows.length===0?<div className="panel empty-state">No {config.label.toLowerCase()} yet.</div>:<div className="content-list">{rows.map((row,index)=><article className="panel content-row" key={row.id}><div><h2>{row.title||row.name||row.position||row.degree||row.label}</h2><p className="muted">{row.company||row.issuer||row.institution||row.organization||row.summary||''}</p></div><div className="row-actions"><span className={row.visible?'pill visible':'pill'}>{row.visible?'Visible':'Hidden'}</span><button aria-label="Move up" disabled={index===0} onClick={()=>move(index,-1)}>↑</button><button aria-label="Move down" disabled={index===rows.length-1} onClick={()=>move(index,1)}>↓</button><button onClick={()=>start(row)}>Edit</button><button className="danger" onClick={()=>remove(row.id)}>Delete</button></div></article>)}</div>}</>;
}
