import Image from 'next/image';import Link from 'next/link';import ContactForm from './contact-form';
function Section({id,title,children}){return <section className="portfolio-section" id={id}><p className="eyebrow">{title}</p>{children}</section>}
function Dates({start,end,current}){return <span>{start}{current?' — Present':end?` — ${end}`:''}</span>}
export default function Portfolio({data}){const {profile:p,settings:s}=data;const enabled=s.enabled_sections||{};const jsonLd={'@context':'https://schema.org','@type':'Person',name:p.name,jobTitle:p.title,url:s.site_url||undefined,email:p.public_email||undefined};return <div style={{'--accent':s.primary_color||'#276348'}} data-mode={s.color_mode||'light'}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd).replace(/</g,'\\u003c')}}/><header className="public-header"><div className="container header-inner"><a className="brand" href="#top"><span className="brand-mark">{(p.name||s.site_name||'p')[0]}</span>{p.name||s.site_name||'Portfolio'}</a><nav className="public-nav" aria-label="Portfolio">{enabled.projects!==false&&<a href="#projects">Work</a>}<a href="#about">About</a>{enabled.contact!==false&&<a href="#contact">Contact</a>}</nav></div></header><main id="main"><section className="public-hero container" id="top"><div>{p.location&&<p className="eyebrow">Based in {p.location}</p>}<h1>{p.name||'Your name'}<br/><span>{p.title||'Your professional title'}</span></h1><p className="lede">{p.short_bio||s.site_description||'Add your introduction from the admin panel.'}</p><div className="hero-actions">{enabled.contact!==false&&<a className="button no-margin" href="#contact">Let’s talk</a>}{p.resume_media_id&&<a className="secondary-link" href={`/api/media/${p.resume_media_id}`}>Download résumé ↓</a>}</div></div>{p.photo_media_id&&<Image className="portrait" src={`/api/media/${p.photo_media_id}`} width={520} height={620} alt={`${p.name} portrait`} priority unoptimized/>}</section><div className="container">
{p.long_bio&&<Section id="about" title="About"><h2>{p.title||'About me'}</h2><p className="section-copy pre-line">{p.long_bio}</p></Section>}
{enabled.experience!==false&&data.experiences.length>0&&<Section id="experience" title="Experience"><div className="timeline">{data.experiences.map((x)=><article key={x.id}><div><h2>{x.position}</h2><p>{x.company}{x.location&&` · ${x.location}`}</p></div><div><p className="muted"><Dates start={x.start_date} end={x.end_date} current={x.is_current}/></p><p className="pre-line">{x.description}</p></div></article>)}</div></Section>}
{enabled.projects!==false&&data.projects.length>0&&<Section id="projects" title="Selected work"><div className="project-grid">{data.projects.map((x)=><article className="project-card" key={x.id}>{x.image_media_id&&<Image src={`/api/media/${x.image_media_id}`} width={640} height={400} alt={x.title} unoptimized/>}<div><p className="muted">{x.technologies.join(' · ')}</p><h2><Link href={`/projects/${x.slug}`}>{x.title}</Link></h2><p>{x.summary}</p></div></article>)}</div></Section>}
{enabled.skills!==false&&data.skills.length>0&&<Section id="skills" title="Skills"><div className="skill-groups">{data.skillCategories.map((category)=><article key={category.id}><h2>{category.name}</h2><p>{data.skills.filter((x)=>x.category_id===category.id).map((x)=>x.name).join(' · ')}</p></article>)}</div></Section>}
{enabled.education!==false&&data.education.length>0&&<Section id="education" title="Education"><div className="simple-grid">{data.education.map((x)=><article key={x.id}><h2>{x.degree}</h2><p>{x.institution}{x.field&&` · ${x.field}`}</p><p className="muted"><Dates start={x.start_date} end={x.end_date}/></p></article>)}</div></Section>}
{enabled.achievements!==false&&data.achievements.length>0&&<Section id="achievements" title="Achievements"><div className="simple-grid">{data.achievements.map((x)=><article key={x.id}><h2>{x.title}</h2><p>{x.description}</p><p className="muted">{x.organization} · {x.date}</p></article>)}</div></Section>}
{enabled.certifications!==false&&data.certifications.length>0&&<Section id="certifications" title="Certifications"><div className="simple-grid">{data.certifications.map((x)=><article key={x.id}><h2>{x.name}</h2><p>{x.issuer}</p><p className="muted">Issued {x.issue_date}</p>{x.credential_url&&<a href={x.credential_url}>View credential ↗</a>}{x.file_media_id&&<a className="block mt-2" href={`/api/media/${x.file_media_id}`}>Download certificate ↓</a>}</article>)}</div></Section>}
{enabled.contact!==false&&<Section id="contact" title="Contact"><div className="contact-grid"><div><h2>Have something in mind?</h2><p className="section-copy">Send a message and I’ll get back to you.</p>{p.public_email&&<a href={`mailto:${p.public_email}`}>{p.public_email}</a>}<div className="socials">{data.socialLinks.map((x)=><a href={x.url} key={x.id}>{x.label} ↗</a>)}</div></div><ContactForm/></div></Section>}</div></main><footer className="site-footer"><div className="container">© {new Date().getFullYear()} {p.name||s.site_name||'Portfolio'}</div></footer></div>}
