"use client";
import { useState } from "react";

const fields=[['name','Name'],['title','Professional title'],['short_bio','Short bio','textarea'],['long_bio','About','textarea'],['location','Location'],['public_email','Public email','email'],['public_phone','Public phone','tel']];
export default function ProfileForm({initial}){const [form,setForm]=useState(initial);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  async function upload(file,kind){if(!file)return null;const data=new FormData();data.set('file',file);data.set('altText',kind==='photo'?`${form.name||'Profile'} portrait`:'Resume');const response=await fetch('/api/admin/media',{method:'POST',body:data});const result=await response.json();if(!response.ok)throw new Error(result.error);return result.data.id;}
  async function save(e){e.preventDefault();const photoFile=e.currentTarget.elements.namedItem('photo')?.files?.[0];const resumeFile=e.currentTarget.elements.namedItem('resume')?.files?.[0];setBusy(true);setMessage('');let photo=null,resume=null;try{photo=await upload(photoFile,'photo');resume=await upload(resumeFile,'resume');const payload={...form,photo_media_id:photo||form.photo_media_id,resume_media_id:resume||form.resume_media_id};const response=await fetch('/api/admin/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error);await Promise.allSettled([photo&&form.photo_media_id?fetch(`/api/admin/media/${form.photo_media_id}`,{method:'DELETE'}):null,resume&&form.resume_media_id?fetch(`/api/admin/media/${form.resume_media_id}`,{method:'DELETE'}):null].filter(Boolean));setForm(payload);setMessage('Profile saved.');}catch(error){if(photo)await fetch(`/api/admin/media/${photo}`,{method:'DELETE'});if(resume)await fetch(`/api/admin/media/${resume}`,{method:'DELETE'});setMessage(error.message);}finally{setBusy(false);}}
  return <form className="panel editor-form" onSubmit={save}>{fields.map(([name,label,type='text'])=><label className="field" key={name}><span>{label}</span>{type==='textarea'?<textarea value={form[name]||''} onChange={(e)=>setForm({...form,[name]:e.target.value})}/>:<input type={type} value={form[name]||''} onChange={(e)=>setForm({...form,[name]:e.target.value})}/>}</label>)}<label className="field"><span>Profile photo</span><input name="photo" type="file" accept="image/jpeg,image/png,image/webp"/>{form.photo_media_id&&<small>Current photo is saved.</small>}</label><label className="field"><span>Resume PDF</span><input name="resume" type="file" accept="application/pdf"/>{form.resume_media_id&&<small>Current resume is saved.</small>}</label>{message&&<p role="status" className={message.includes('saved')?'form-success':'form-message'}>{message}</p>}<button className="button no-margin" disabled={busy}>{busy?'Saving…':'Save profile'}</button></form>;
}
